export const GET_ADDRESSES = 'GET_ADDRESSES';
export const GET_ADDRESSES_SUCCESS = 'GET_ADDRESSES_SUCCESS';
export const GET_ADDRESSES_ERROR = 'GET_ADDRESSES_ERROR';

export const GET_ADDRESS_NAMES = 'GET_ADDRESS_NAMES';
export const GET_ADDRESS_NAMES_SUCCESS = 'GET_ADDRESS_NAMES_SUCCESS';
export const GET_ADDRESS_NAMES_ERROR = 'GET_ADDRESS_NAMES_ERROR';
